name: "testing on all PUSH and PR"
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  testing:
    name: Testing on 

    runs-on:  ${{ matrix.os}}

    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos, macos-latest]
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Using node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Prepare shell 
        run: |
          set -euo pipefail
          set -x
      
      - name: Prepare linux
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-16.04' || matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt install encfs -y
          mkdir -p ~/cryptobox/ && echo "12345" > ~/cryptobox/pass.txt
          npm ci
          npm test
          
      - name: Prepare MAC
        if: matrix.os == 'macos-latest' || matrix.os == 'macos'
        run: |
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew cask install osxfuse
          brew install encfs
          sudo security unlock-keychain -u
          npm ci
          # npm run make


      # - name: Running the tests with node ${{ matrix.node-version }} and ${{ matrix.os}}
      #   run: |
      #       npm ci
      #       npm test

